# @package _global_
defaults:
  - _self_
  - unsloth/default

model:
    model_name: "unsloth/Phi-3-mini-4k-instruct"
    max_seq_length: null
    dtype: null # null for auto detection. Float16 for Tesla T4, V100, Bfloat16 for Ampere+
    load_in_4bit: False

tokenizer:
  padding_side: "left" 
  truncation_side: "left" # to prevent cutting off last generation
  pad_token: "eos_token"
  add_eos_token: True
  use_fast: True