_target_: src.data.data_recipe.DataRecipe

# How many samples to keep in the dataset after computing the 
# distribution of sequence lengths.
keep_percentile: 100

# Max number of samples used for evaluation
max_eval_samples: 1000

# Whether to use the full dataset including val data to train
full_train: false